version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cartoon_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
